/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UnionBD;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.DefaultListModel;

public class FrmBD extends javax.swing.JFrame {

    /**
     * Creates new form FrmBD
     */
    public FrmBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMySQL = new javax.swing.JButton();
        btnSQLServer = new javax.swing.JButton();
        btnMostrarMySQL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbTablas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbRegistros = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbBaseDatos = new javax.swing.JList<>();
        btnMostrarSQL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMySQL.setText("MySQL");
        btnMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMySQLActionPerformed(evt);
            }
        });

        btnSQLServer.setText("SQLServer");
        btnSQLServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSQLServerActionPerformed(evt);
            }
        });

        btnMostrarMySQL.setText("Mostrar MySQL");
        btnMostrarMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMySQLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Base de Datos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tablas");

        jScrollPane2.setViewportView(lbTablas);

        jScrollPane3.setViewportView(lbRegistros);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Registros");

        jScrollPane1.setViewportView(lbBaseDatos);

        btnMostrarSQL.setText("Mostrar SQLServer");
        btnMostrarSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSQLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarMySQL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMySQL)
                                    .addComponent(btnSQLServer))
                                .addGap(63, 63, 63)
                                .addComponent(btnMostrarSQL)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMySQL)
                    .addComponent(btnMostrarMySQL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSQLServer)
                    .addComponent(btnMostrarSQL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMySQLActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn =DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql",
                    "root","");
            Statement stm = cn.createStatement();
            ResultSet rs = stm.executeQuery("show databases");
            DefaultListModel dlm = new DefaultListModel();
            while(rs.next()){
                dlm.add(0,rs.getString(1));
            }
            lbBaseDatos.setModel(dlm);
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnMySQLActionPerformed

    private void btnSQLServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSQLServerActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection cn =DriverManager.getConnection("jdbc:sqlserver://95.217.180.168:1433;database=ControlPV;Encrypt=false",
                    "sa","01K#cjWq3c");
            Statement stm = cn.createStatement();
            String sql = "select * from sys.databases where is_broker_enabled = 1";
            ResultSet rs = stm.executeQuery(sql);
            DefaultListModel dlm = new DefaultListModel();
            while(rs.next()){
                dlm.add(0,rs.getString(1));
            }
            lbBaseDatos.setModel(dlm);
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSQLServerActionPerformed

    private void btnMostrarMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMySQLActionPerformed
        try{
            String db = lbBaseDatos.getSelectedValue();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn =DriverManager.getConnection("jdbc:mysql://localhost:3306/"+db,
                    "root","");
            Statement stm = cn.createStatement();
            //stm.executeQuery("use controlpv");
            ResultSet rs = stm.executeQuery("show tables");
            DefaultListModel dlm = new DefaultListModel();
            while(rs.next()){
                dlm.add(0,rs.getString(1));
            }
            lbTablas.setModel(dlm);
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnMostrarMySQLActionPerformed

    private void btnMostrarSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSQLActionPerformed
        try{
            String db = lbBaseDatos.getSelectedValue();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection cn =DriverManager.getConnection("jdbc:sqlserver://95.217.180.168:1433;database=ControlPV;Encrypt=false",
                    "sa","01K#cjWq3c");
            Statement stm = cn.createStatement();
            String sql = "select * from sys.databases where is_broker_enabled = 1";
            ResultSet rs = stm.executeQuery(sql);
            DefaultListModel dlm = new DefaultListModel();
            while(rs.next()){
                dlm.add(0,rs.getString(1));
            }
            lbBaseDatos.setModel(dlm);
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnMostrarSQLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarMySQL;
    private javax.swing.JButton btnMostrarSQL;
    private javax.swing.JButton btnMySQL;
    private javax.swing.JButton btnSQLServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lbBaseDatos;
    private javax.swing.JList<String> lbRegistros;
    private javax.swing.JList<String> lbTablas;
    // End of variables declaration//GEN-END:variables
}
