/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.SolicitudViatico;
import Clases.Viatico;
import EstructuraDeDatos.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;


public class FrmRegistrarSolicitudViatico extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    TableRowSorter trsFiltro;
    
    
        
    
    private DefaultTableModel dtm;
    //private Object[] o=new Object[7];*/
    public ArregloSolicitudViatico arreglo1=new ArregloSolicitudViatico();
    
    
    
   // private ArregloSolicitudViatico arraySV=new ArregloSolicitudViatico(1);
     
   // private SolicitudViatico sv1=new SolicitudViatico();
    
    
    
    
    /**
     * Creates new form frmRegistrarSolicitud
     */
    public FrmRegistrarSolicitudViatico() {
        initComponents();
        this.jTListado.setModel(modelo);
        this.modelo.addColumn("Codigo de Solicitud");
        this.modelo.addColumn("Codigo del Remitente");
        this.modelo.addColumn("Monto");
        this.modelo.addColumn("Tipo de Viaje");
        this.modelo.addColumn("Fecha de Ida");
        this.modelo.addColumn("Fecha de Retorno");
        this.modelo.addColumn("Fecha de la Solicitud");
        //dtm= (DefaultTableModel) jTListado.getModel();
        
        RegistroSV = new javax.swing.JPanel();
        
        // Añade el panel1 al JFrame
        getContentPane().add(RegistroSV, java.awt.BorderLayout.CENTER);
        RegistroSV.setVisible(false);  // Oculta el panel al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        ListadoSV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        tfBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTListado = new javax.swing.JTable();
        RegistroSV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCodigoSolicitud = new javax.swing.JTextField();
        tfCodigoRemitente = new javax.swing.JTextField();
        tfFechaIda = new javax.swing.JTextField();
        tfFechaRetorno = new javax.swing.JTextField();
        tfMonto = new javax.swing.JTextField();
        cbxTipoViaje = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Búsqueda de solicitud:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/find.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pencil_add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/to_do_list_cheked_all.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tfBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBusquedaActionPerformed(evt);
            }
        });

        jTListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTListadoMouseClicked(evt);
            }
        });
        jTListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTListadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTListado);

        javax.swing.GroupLayout ListadoSVLayout = new javax.swing.GroupLayout(ListadoSV);
        ListadoSV.setLayout(ListadoSVLayout);
        ListadoSVLayout.setHorizontalGroup(
            ListadoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoSVLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addGap(54, 54, 54))
            .addGroup(ListadoSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        ListadoSVLayout.setVerticalGroup(
            ListadoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoSVLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ListadoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListadoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListadoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(btnNuevo)
                        .addComponent(btnEditar)
                        .addComponent(btnEliminar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jTabbedPane4.addTab("Listado de Solicitudes", ListadoSV);

        RegistroSV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo de solicitud:");
        RegistroSV.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel3.setText("Codigo de Remitente:");
        RegistroSV.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel4.setText("Fecha de Ida:");
        RegistroSV.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel5.setText("Fecha de Retorno:");
        RegistroSV.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabel6.setText("Tipo de Viaje:");
        RegistroSV.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 80, -1));

        jLabel7.setText("Monto de Viatico:");
        RegistroSV.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 100, -1));

        tfCodigoSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoSolicitudActionPerformed(evt);
            }
        });
        RegistroSV.add(tfCodigoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, -1));
        RegistroSV.add(tfCodigoRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 120, -1));
        RegistroSV.add(tfFechaIda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, -1));
        RegistroSV.add(tfFechaRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 120, -1));
        RegistroSV.add(tfMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 110, -1));

        cbxTipoViaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Nacional", "Internacional", " " }));
        RegistroSV.add(cbxTipoViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 120, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save_as.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        RegistroSV.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 130, 40));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel8.setText("SOLICITUD DE VIATICO");
        RegistroSV.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 410, -1));

        jLabel9.setText("Fecha de envio de la solicitud:");
        RegistroSV.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        tfFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFechaActionPerformed(evt);
            }
        });
        RegistroSV.add(tfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 120, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("//");
        RegistroSV.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jTabbedPane4.addTab("Registro de Solicitud", RegistroSV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoSolicitudActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     
       CrearArregloSV();
       
       this.modelo.addRow(new Object[]{
            this.tfCodigoSolicitud.getText(),
            this.tfCodigoRemitente.getText(),
            this.tfMonto.getText(),
            this.cbxTipoViaje.getSelectedItem(),
            this.tfFechaIda.getText(),
            this.tfFechaRetorno.getText(),
            this.tfFecha.getText(),
        
        });
       
       JOptionPane.showMessageDialog(this, "La solicitud de Viatico se ha registrado existosamente.");
        
       //LIMPIAR
        tfCodigoSolicitud.setText("");
        tfCodigoRemitente.setText("");
        tfFechaIda.setText("");
        tfFechaRetorno.setText("");
        tfMonto.setText("");
        tfFecha.setText("");
        cbxTipoViaje.setSelectedIndex(0);
      
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTListadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTListadoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTListadoKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       // String cod=tfBusqueda.getText();
       // int i=0;
        
        
        
        for(int i=0; i<=dtm.getRowCount(); i++){
           if(tfBusqueda.getText().equals(arreglo1.getSolicitudViaticoByIndex(i).getCodSolicitud())){
               trsFiltro=new TableRowSorter(jTListado.getModel());
               jTListado.setRowSorter(trsFiltro); 
               trsFiltro.setRowFilter(RowFilter.regexFilter(tfBusqueda.getText(), 0));
               break;
           
          
        } 
       
        //String bqd=tfBusqueda.getText();
        
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        if (RegistroSV.isVisible()) {
        RegistroSV.setVisible(false);
        } else {
        RegistroSV.setVisible(true);
        
        
    }
        
        //LIMPIAR
        tfCodigoSolicitud.setText("");
        tfCodigoRemitente.setText("");
        tfFechaIda.setText("");
        tfFechaRetorno.setText("");
        tfMonto.setText("");
        tfFecha.setText("");
        cbxTipoViaje.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFechaActionPerformed

    private void tfBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBusquedaActionPerformed
   int filas;
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String []datos=new String[7];
        datos[0]=tfCodigoSolicitud.getText();
        datos[1]=tfCodigoRemitente.getText();
        datos[2]=tfMonto.getText();
        datos[3]=cbxTipoViaje.getSelectedItem().toString();
        datos[4]=tfFechaIda.getText();
        datos[5]=tfFechaRetorno.getText();
        datos[6]=tfFecha.getText();

        
        for(int i=0; i<jTListado.getColumnCount();i++){
            modelo.setValueAt(datos[i], filas, i);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila_seleccionada = jTListado.getSelectedRow();
        if(fila_seleccionada>=0){
            modelo.removeRow(fila_seleccionada);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila por favor");
        }
        
        tfCodigoSolicitud.setText("");
        tfCodigoRemitente.setText("");
        tfFechaIda.setText("");
        tfFechaRetorno.setText("");
        tfMonto.setText("");
        tfFecha.setText("");
        cbxTipoViaje.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTListadoMouseClicked
        int fila_seleccionada = jTListado.getSelectedRow();
        tfCodigoSolicitud.setText(jTListado.getValueAt(fila_seleccionada, 0).toString());
        tfCodigoRemitente.setText(jTListado.getValueAt(fila_seleccionada, 1).toString());
        tfMonto.setText(jTListado.getValueAt(fila_seleccionada, 2).toString());
        cbxTipoViaje.setSelectedItem(jTListado.getValueAt(fila_seleccionada, 3).toString());
        tfFechaIda.setText(jTListado.getValueAt(fila_seleccionada, 4).toString());
        tfFechaRetorno.setText(jTListado.getValueAt(fila_seleccionada, 5).toString());
        tfFecha.setText(jTListado.getValueAt(fila_seleccionada, 6).toString());
        
        filas=fila_seleccionada;
    }//GEN-LAST:event_jTListadoMouseClicked
    private void Limpiar() {
        tfCodigoSolicitud.setText("");
        tfCodigoRemitente.setText("");
        tfFechaIda.setText("");
        tfFechaRetorno.setText("");
        tfMonto.setText("");
        tfFecha.setText("");
        cbxTipoViaje.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarSolicitudViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarSolicitudViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarSolicitudViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarSolicitudViatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarSolicitudViatico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListadoSV;
    private javax.swing.JPanel RegistroSV;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbxTipoViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTListado;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField tfBusqueda;
    private javax.swing.JTextField tfCodigoRemitente;
    private javax.swing.JTextField tfCodigoSolicitud;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfFechaIda;
    private javax.swing.JTextField tfFechaRetorno;
    private javax.swing.JTextField tfMonto;
    // End of variables declaration//GEN-END:variables

    private void CrearArregloSV() {
        
       
        
        
        arreglo1.addSolicitudViatico(new SolicitudViatico(tfCodigoSolicitud.getText(), 
        tfCodigoRemitente.getText(), tfFecha.getText(), tfFechaIda.getText(),
        tfFechaRetorno.getText(),cbxTipoViaje.getSelectedItem().toString(),new Viatico(Double.parseDouble(tfMonto.getText()))));
        
       // System.out.println(arreglo1.getSolicitudViaticoByIndex(0).getFechaIda());
        
        /*o[0]=tfCodigoSolicitud.getText().trim();
        //o[0]=arreglo1.getSolicitudViaticoByIndex(0).getCodSolicitud();
        o[1]=tfCodigoRemitente.getText().trim();
        //o[1]=arreglo1.getSolicitudViaticoByIndex(0).getCodRemitente();
        o[2]=tfFecha.getText();
        //o[2]=arreglo1.getSolicitudViaticoByIndex(0).getFechaSolicitud();
        o[3]=cbxTipoViaje.getSelectedItem().toString();
        //o[3]=arreglo1.getSolicitudViaticoByIndex(0).getTipoViaje();
        o[4]=tfFechaIda.getText();
        //o[4]=arreglo1.getSolicitudViaticoByIndex(0).getFechaIda();
        o[5]=tfFechaRetorno.getText().trim();
        //o[5]=arreglo1.getSolicitudViaticoByIndex(0).getFechaRetorno();
        o[6]=tfMonto.getText();
        //o[6]=arreglo1.getSolicitudViaticoByIndex(0).getMonto();
        dtm.addRow(o);*/
    }

    

    

    
}
